# Generated by Django 6.0.1 on 2026-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Project Title', max_length=30)),
                ('subtitle', models.TextField(help_text='Short Project Subtitle', max_length=70)),
                ('author', models.TextField(help_text='Project Creator', max_length=70)),
                ('description', models.TextField(help_text='Project Description', max_length=10000)),
                ('preferred_skills', models.TextField(help_text='Preferred Skills', max_length=300)),
            ],
        ),
    ]
