# Generated by Django 6.0.1 on 2026-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Project Title', max_length=30)),
                ('short_description', models.TextField(default='', help_text='Short Project Description', max_length=500)),
                ('author', models.TextField(help_text='Project Creator', max_length=70)),
                ('author_id', models.IntegerField()),
                ('extended_description', models.TextField(default='', help_text='Project Description', max_length=10000)),
                ('preferred_skills', models.JSONField(default=list)),
                ('project_type', models.TextField(default='Other', help_text='Project Type', max_length=50)),
                ('workload_per_week', models.TextField(default='', help_text='Workload', max_length=50)),
                ('preferred_contact_method', models.TextField(default='', help_text='Preferred Contact Method', max_length=50)),
                ('contact_information', models.TextField(default='', help_text='Contact Information', max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('misleading', 'Misleading Information'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
