# Generated by Django 6.0.1 on 2026-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='project',
            name='contact_information',
            field=models.TextField(default='', help_text='Contact Information', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='extended_description',
            field=models.TextField(default='', help_text='Project Description', max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='preferred_contact_method',
            field=models.TextField(default='', help_text='Preferred Contact Method', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.TextField(default='Other', help_text='Project Type', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='', help_text='Short Project Description', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='workload_per_week',
            field=models.TextField(default='', help_text='Workload', max_length=50),
        ),
    ]
