# Generated by Django 6.0.1 on 2026-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_remove_project_description_remove_project_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preferred_skills',
            field=models.JSONField(default=list),
        ),
    ]
