# Generated by Django 5.2.10 on 2026-02-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_project_preferred_skills'),
        ('project_management', '0004_join_request'),
    ]

    operations = [
    ]
