# Generated by Django 6.0.1 on 2026-02-24 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_project_preferred_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
