# Generated by Django 6.0.1 on 2026-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_project_creation_time_project_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
