# Generated by Django 6.0.1 on 2026-03-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_project_author_id'),
        ('project_management', '0006_report'),
    ]

    operations = [
    ]
