# Generated by Django 6.0.1 on 2026-03-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_join_request'),
        ('project_management', '0007_merge_0006_project_author_id_0006_report'),
    ]

    operations = [
    ]
