from sqlite3 import IntegrityError
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, JsonResponse
from functools import partial
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import json
import ollama

from llm_integration.tool_functions import create_link_to_project, get_profile, get_project, list_projects
from project_management.views import LOGIN_PAGE_URL

SYSTEM_PROMPT = """
You are an assistant that helps students find existing projects to join. Use the tools provided to answer all requests.

Available Tools:

- list_projects – Returns a brief overview of all available projects.
- get_project(id: integer) – Returns detailed information about a specific project by ID.
- get_self_profile – Returns the current user's interests, skills, and availability.
- get_profile(id: integer) – Returns another user's interests, skills, and availability by user ID.
- link_to_project(id: integer) – Generates a clickable link to a project's page.

Recommending Projects — Step-by-Step:

Follow these steps in order every time you recommend projects (for when the user asks for recommendations):

1. Determine how many recommendations to make. Unless the user specifies a number, default to min(3, floor(total_projects / 2)). You will get total_projects from list_projects in step 3.
2. Fetch the user's profile. Call get_self_profile to retrieve their interests, skills, and availability. Note: if the user has stated preferences directly in their message, prioritize those over their profile data — use their profile only to fill in any gaps.
3. Get all available projects. Call list_projects to retrieve the full list of projects. Use the user's profile and stated preferences to identify the most relevant candidates.
4. Get details on candidate projects. Call get_project(id) for each project you think may be a good fit. Gather enough candidates to meet the recommendation count determined in step 1.
5. Respond with your recommendations as a numbered list. Each item must include:

    - Project Summary – A brief description of what the project is about and its goals.
    - What's Required – The relevant skills, expected workload, and availability needed to contribute.
    - Project Link – A link generated by calling link_to_project(id).

Key Rules:

- Always complete all steps before responding — do not recommend a project without first calling get_project on it.
- Never recommend a project based on list_projects data alone; always fetch full details first.
- If no projects are a good match, tell the user honestly rather than forcing poor recommendations.
"""

@csrf_exempt
@login_required(login_url=LOGIN_PAGE_URL)
def prompt_llm(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return HttpResponseBadRequest(b"HTTP method must be POST")

    json_body: dict[str, str] = dict(json.loads(request.body))

    user_id = request.user.id
    base_url = request.build_absolute_uri('/')
    get_self_profile = partial(get_profile, user_id=user_id)
    link_to_project = partial(create_link_to_project, base_url=base_url)

    available_tools= {
        'list_projects': list_projects,
        'get_project': get_project,
        'get_self_profile': get_self_profile,
        'get_profile': get_profile,
        'link_to_project': link_to_project,
    }


    tools = [list_projects, get_project, get_self_profile, get_profile, link_to_project]

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": json_body.get("prompt")},
    ]

    for i in range(25):
        try:
            response = ollama.chat(
                model="nemotron-3-nano:4b",
                messages=messages,
                tools=tools,
            )
        except Exception as e:
            return HttpResponseBadRequest(f"ollama.chat failed on iteration {i + 1}: {e}".encode())

        message = response["message"]
        messages.append(message)

        tool_calls = message.get("tool_calls") or []
        if not tool_calls:
            return JsonResponse({"success": True, "response": message["content"]})

        for tool_call in tool_calls:
            fn_name = tool_call["function"]["name"]
            fn_args = tool_call["function"]["arguments"]
            fn = available_tools.get(fn_name)
            if fn is None:
                return HttpResponseBadRequest(f"LLM requested unknown tool '{fn_name}' on iteration {i + 1}".encode())
            try:
                result = fn(**fn_args)
            except Exception as e:
                return HttpResponseBadRequest(f"Tool '{fn_name}' raised an exception on iteration {i + 1}: {e}".encode())
            messages.append({"role": "tool", "content": json.dumps(result)})

    return HttpResponseBadRequest(b"Reached 25-call limit without a final response from the LLM")
