
# Generated by Django 6.0.1 on 2026-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabouser',
            name='availability',
            field=models.TextField(default='', help_text='Availability', max_length=500),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='contact_information',
            field=models.TextField(default='', help_text='Contact Information', max_length=100),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='major',
            field=models.TextField(default='', help_text='Major', max_length=50),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='preferred_contact_method',
            field=models.TextField(default='', help_text='Preferred Contact Method', max_length=50),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
