# Generated by Django 6.0.1 on 2026-03-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_collabouser_availability_and_more'),
        ('user_authentication', '0002_passwordresettoken'),
    ]

    operations = [
    ]
