# Generated by Django 6.0.1 on 2026-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_collabouser_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabouser',
            name='active_project_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='project_expiration_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collabouser',
            name='weekly_update_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
