# Generated by Django 6.0.1 on 2026-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_collabouser_active_project_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabouser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='collabouser',
            name='weekly_update_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
