# Generated by Django 6.0.1 on 2026-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_alter_collabouser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabouser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
