# Generated by Django 6.0.1 on 2026-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_collabouser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabouser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
